.TH "D:/JAVA workspace/EightQueen/EightQueen.cpp" 3 "Sun Mar 25 2012" "Version 1.0" "EightQueen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/JAVA workspace/EightQueen/EightQueen.cpp \- 
.PP
Definition of \fBEightQueen\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'EightQueen\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <ostream>\fP
.br

.SH "Detailed Description"
.PP 
Definition of \fBEightQueen\fP class\&. 

\fBAuthor:\fP
.RS 4
: yjq 
.RE
.PP
\fBDate:\fP
.RS 4
2012-3-25 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for EightQueen from the source code\&.
