.TH "EightQueen" 3 "Sun Mar 25 2012" "Version 1.0" "EightQueen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EightQueen \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EightQueen\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEightQueen\fP ()"
.br
.ti -1c
.RI "virtual \fB~EightQueen\fP ()"
.br
.ti -1c
.RI "std::vector< int > \fBSafePut\fP (int index)"
.br
.ti -1c
.RI "void \fBPrintQueen\fP ()"
.br
.ti -1c
.RI "bool \fBCheckSafe\fP (int index)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEightQueen::EightQueen\fP ()"

.SS "\fBEightQueen::~EightQueen\fP ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool \fBEightQueen::CheckSafe\fP (intindex)"

.SS "void \fBEightQueen::PrintQueen\fP ()"

.SS "std::vector< int > \fBEightQueen::SafePut\fP (intindex)"


.SH "Author"
.PP 
Generated automatically by Doxygen for EightQueen from the source code\&.
