.TH "D:/JAVA workspace/EightQueen/EightQueen.h" 3 "Sun Mar 25 2012" "Version 1.0" "EightQueen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/JAVA workspace/EightQueen/EightQueen.h \- 
.PP
Declare \fBEightQueen\fP class definition available at \fBEightQueen\&.cpp\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEightQueen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declare \fBEightQueen\fP class definition available at \fBEightQueen\&.cpp\fP\&. 

\fBAuthor:\fP
.RS 4
: yjq 
.RE
.PP
\fBDate:\fP
.RS 4
2012-3-25 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for EightQueen from the source code\&.
