.TH "D:/JAVA workspace/EightQueen/main.cpp" 3 "Sun Mar 25 2012" "Version 1.0" "EightQueen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/JAVA workspace/EightQueen/main.cpp \- 
.PP
run the eightqueen problem  

.SH SYNOPSIS
.br
.PP
\fC#include 'EightQueen\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
run the eightqueen problem 

\fBAuthor:\fP
.RS 4
yjq 
.RE
.PP
\fBDate:\fP
.RS 4
2012-3-25 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int \fBmain\fP ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for EightQueen from the source code\&.
